# environment:
  # matrix:
  # - JAVA_HOME: C:\Program Files\Java\jdk1.7.0 currently default in path

# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

build_script:
  - mvn install -DskipTests

 # verify artifacts
test_script:
  - mvn verify

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
